name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linter: 
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1

  iOS:
    name: Build and Test.
    runs-on: macos-11
    env:
      DEVELOPER_DIR: '/Applications/Xcode_12.5.app/Contents/Developer'
      XCODE_SCHEME: "JWWUIKit"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Test (iOS)
        run: | 
          set -o pipefail && env NSUnbufferedIO=YES 
          xcodebuild build-for-testing -scheme $XCODE_SCHEME -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty

      - name: Build and Test (tvOS)
        run: | 
          set -o pipefail && env NSUnbufferedIO=YES 
          xcodebuild build-for-testing -scheme $XCODE_SCHEME -destination "platform=tvOS Simulator,OS=latest,name=Apple TV 4K" | xcpretty
